<HTML>
<HEAD>
    <TITLE>{$project} - Page Index</TITLE>
</HEAD>
<BODY bgcolor="#ffffff">
<nav id="main">
    <a href="index.html">Home</a>
    <hr>
</nav>

{$content}

<footer>
    <hr>
    <p>Generated by <a href="http://stevegeek.github.com/CompileDocs">CompileDocs</a> on {$generated}</p>
</footer>
</BODY>
</HTML>
