<HTML>
<HEAD>
    <TITLE>{$project} - {$name}</TITLE>
</HEAD>
<BODY bgcolor="#ffffff">
<nav id="main">
<a href="index.html">Home</a> - <a href="{$prev}">Prev</a> - <a href="{$next}">Next</a> - <a href="_docs_index.html">Index</a>
<hr></nav>

{$content}

    <footer>
    <hr>
    <p>Generated by <a href="http://stevegeek.github.com/CompileDocs">CompileDocs</a> on {$generated}</p>
    </footer>
</BODY>
</HTML>
